# Generated by Django 4.2.1 on 2023-06-28 14:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nom_marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nom_producto', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField(max_length=300)),
                ('stock', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('R', 'Retirado'), ('NR', 'No Retirado')], default=('NR', 'No Retirado'), max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, upload_to='Productos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('run', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ]*$', 'Ingrese solo letras')])),
                ('segundo_nombre', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ]*$', 'Ingrese solo letras')])),
                ('apellido_paterno', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ]*$', 'Ingrese solo letras')])),
                ('apellido_materno', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ]*$', 'Ingrese solo letras')])),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
