# Generated by Django 4.2.1 on 2023-06-27 21:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('run', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ]*$', 'Ingrese solo letras')])),
                ('segundo_nombre', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ]*$', 'Ingrese solo letras')])),
                ('apellido_paterno', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ]*$', 'Ingrese solo letras')])),
                ('apellido_materno', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-ZñÑ]*$', 'Ingrese solo letras')])),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
