# Generated by Django 4.2.1 on 2023-06-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pedido_usuario_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('R', 'Retirado'), ('NR', 'No Retirado')], default=('NR', 'No Retirado'), max_length=50),
        ),
    ]
